# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'spi_v1_main.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFormLayout,
    QFrame, QGridLayout, QHBoxLayout, QLabel,
    QLineEdit, QListWidget, QListWidgetItem, QPlainTextEdit,
    QPushButton, QRadioButton, QSizePolicy, QSplitter,
    QStackedWidget, QTabWidget, QTextBrowser, QVBoxLayout,
    QWidget)

class Ui_MainForm(object):
    def setupUi(self, MainForm):
        if not MainForm.objectName():
            MainForm.setObjectName(u"MainForm")
        MainForm.resize(1300, 800)
        MainForm.setMinimumSize(QSize(1300, 800))
        MainForm.setMaximumSize(QSize(2500, 1500))
        self.gridLayout_6 = QGridLayout(MainForm)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.splitter = QSplitter(MainForm)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.button_prj = QPushButton(self.splitter)
        self.button_prj.setObjectName(u"button_prj")
        self.button_prj.setMaximumSize(QSize(100, 25))
        font = QFont()
        font.setPointSize(10)
        self.button_prj.setFont(font)
        self.splitter.addWidget(self.button_prj)
        self.button_spi = QPushButton(self.splitter)
        self.button_spi.setObjectName(u"button_spi")
        self.button_spi.setMaximumSize(QSize(100, 25))
        self.button_spi.setFont(font)
        self.splitter.addWidget(self.button_spi)
        self.button_hard = QPushButton(self.splitter)
        self.button_hard.setObjectName(u"button_hard")
        self.button_hard.setMaximumSize(QSize(100, 25))
        self.button_hard.setFont(font)
        self.splitter.addWidget(self.button_hard)
        self.button_setting = QPushButton(self.splitter)
        self.button_setting.setObjectName(u"button_setting")
        self.button_setting.setMaximumSize(QSize(100, 25))
        self.button_setting.setFont(font)
        self.splitter.addWidget(self.button_setting)

        self.gridLayout_6.addWidget(self.splitter, 0, 0, 1, 1)

        self.stacked_widget = QStackedWidget(MainForm)
        self.stacked_widget.setObjectName(u"stacked_widget")
        self.stacked_widget.setMinimumSize(QSize(0, 0))
        self.stacked_widget.setLineWidth(1)
        self.Main = QWidget()
        self.Main.setObjectName(u"Main")
        self.gridLayout_4 = QGridLayout(self.Main)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(5, 0, 5, 0)
        self.main_widget = QWidget(self.Main)
        self.main_widget.setObjectName(u"main_widget")
        self.main_widget.setMinimumSize(QSize(0, 0))
        self.gridLayout_2 = QGridLayout(self.main_widget)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.data_widget = QWidget(self.main_widget)
        self.data_widget.setObjectName(u"data_widget")
        self.gridLayout = QGridLayout(self.data_widget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.verticalLayout_7 = QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.button_add_group = QPushButton(self.data_widget)
        self.button_add_group.setObjectName(u"button_add_group")
        self.button_add_group.setMaximumSize(QSize(50, 25))

        self.horizontalLayout_8.addWidget(self.button_add_group)

        self.button_del_group = QPushButton(self.data_widget)
        self.button_del_group.setObjectName(u"button_del_group")
        self.button_del_group.setMaximumSize(QSize(50, 25))

        self.horizontalLayout_8.addWidget(self.button_del_group)

        self.combo_box_group = QComboBox(self.data_widget)
        self.combo_box_group.setObjectName(u"combo_box_group")
        self.combo_box_group.setMaximumSize(QSize(150, 25))

        self.horizontalLayout_8.addWidget(self.combo_box_group)

        self.button_del_select = QPushButton(self.data_widget)
        self.button_del_select.setObjectName(u"button_del_select")
        self.button_del_select.setMaximumSize(QSize(31, 21))

        self.horizontalLayout_8.addWidget(self.button_del_select)


        self.verticalLayout_7.addLayout(self.horizontalLayout_8)

        self.list_group = QListWidget(self.data_widget)
        self.list_group.setObjectName(u"list_group")
        self.list_group.setMinimumSize(QSize(299, 0))
        self.list_group.setMaximumSize(QSize(300, 16777215))
        font1 = QFont()
        font1.setPointSize(16)
        self.list_group.setFont(font1)

        self.verticalLayout_7.addWidget(self.list_group)

        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.radio_button_order = QRadioButton(self.data_widget)
        self.radio_button_order.setObjectName(u"radio_button_order")
        self.radio_button_order.setMinimumSize(QSize(0, 0))
        self.radio_button_order.setMaximumSize(QSize(295, 29))
        font2 = QFont()
        font2.setPointSize(14)
        self.radio_button_order.setFont(font2)

        self.verticalLayout_4.addWidget(self.radio_button_order)

        self.radio_button_circ = QRadioButton(self.data_widget)
        self.radio_button_circ.setObjectName(u"radio_button_circ")
        self.radio_button_circ.setMinimumSize(QSize(0, 0))
        self.radio_button_circ.setMaximumSize(QSize(295, 25))
        self.radio_button_circ.setFont(font2)

        self.verticalLayout_4.addWidget(self.radio_button_circ)

        self.radio_button_random = QRadioButton(self.data_widget)
        self.radio_button_random.setObjectName(u"radio_button_random")
        self.radio_button_random.setMinimumSize(QSize(0, 0))
        self.radio_button_random.setMaximumSize(QSize(295, 25))
        self.radio_button_random.setFont(font2)

        self.verticalLayout_4.addWidget(self.radio_button_random)

        self.splitter_11 = QSplitter(self.data_widget)
        self.splitter_11.setObjectName(u"splitter_11")
        self.splitter_11.setOrientation(Qt.Orientation.Horizontal)
        self.label_5 = QLabel(self.splitter_11)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setMaximumSize(QSize(83, 25))
        self.label_5.setFont(font2)
        self.splitter_11.addWidget(self.label_5)
        self.line_delay = QLineEdit(self.splitter_11)
        self.line_delay.setObjectName(u"line_delay")
        self.line_delay.setMinimumSize(QSize(150, 0))
        self.line_delay.setMaximumSize(QSize(200, 25))
        font3 = QFont()
        font3.setPointSize(12)
        self.line_delay.setFont(font3)
        self.splitter_11.addWidget(self.line_delay)

        self.verticalLayout_4.addWidget(self.splitter_11)

        self.splitter_12 = QSplitter(self.data_widget)
        self.splitter_12.setObjectName(u"splitter_12")
        self.splitter_12.setOrientation(Qt.Orientation.Horizontal)
        self.label_2 = QLabel(self.splitter_12)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMinimumSize(QSize(60, 0))
        self.label_2.setMaximumSize(QSize(83, 25))
        self.label_2.setFont(font2)
        self.splitter_12.addWidget(self.label_2)
        self.line_number = QLineEdit(self.splitter_12)
        self.line_number.setObjectName(u"line_number")
        self.line_number.setMinimumSize(QSize(150, 0))
        self.line_number.setMaximumSize(QSize(200, 25))
        self.line_number.setFont(font3)
        self.splitter_12.addWidget(self.line_number)

        self.verticalLayout_4.addWidget(self.splitter_12)


        self.horizontalLayout_7.addLayout(self.verticalLayout_4)


        self.verticalLayout_7.addLayout(self.horizontalLayout_7)

        self.splitter_7 = QSplitter(self.data_widget)
        self.splitter_7.setObjectName(u"splitter_7")
        self.splitter_7.setOrientation(Qt.Orientation.Horizontal)
        self.button_start = QPushButton(self.splitter_7)
        self.button_start.setObjectName(u"button_start")
        self.button_start.setMinimumSize(QSize(0, 0))
        self.button_start.setMaximumSize(QSize(147, 25))
        self.button_start.setFont(font)
        self.splitter_7.addWidget(self.button_start)
        self.button_stop = QPushButton(self.splitter_7)
        self.button_stop.setObjectName(u"button_stop")
        self.button_stop.setMinimumSize(QSize(0, 0))
        self.button_stop.setMaximumSize(QSize(147, 25))
        self.button_stop.setFont(font)
        self.splitter_7.addWidget(self.button_stop)

        self.verticalLayout_7.addWidget(self.splitter_7)


        self.horizontalLayout.addLayout(self.verticalLayout_7)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.splitter_5 = QSplitter(self.data_widget)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setOrientation(Qt.Orientation.Horizontal)
        self.label = QLabel(self.splitter_5)
        self.label.setObjectName(u"label")
        self.label.setMinimumSize(QSize(26, 25))
        self.label.setFont(font)
        self.splitter_5.addWidget(self.label)
        self.combo_box_data_group = QComboBox(self.splitter_5)
        self.combo_box_data_group.setObjectName(u"combo_box_data_group")
        self.combo_box_data_group.setMinimumSize(QSize(100, 25))
        self.splitter_5.addWidget(self.combo_box_data_group)
        self.button_rename = QPushButton(self.splitter_5)
        self.button_rename.setObjectName(u"button_rename")
        self.button_rename.setMinimumSize(QSize(79, 25))
        self.button_rename.setMaximumSize(QSize(16777215, 16777215))
        self.button_rename.setFont(font)
        self.splitter_5.addWidget(self.button_rename)
        self.button_import = QPushButton(self.splitter_5)
        self.button_import.setObjectName(u"button_import")
        self.button_import.setMinimumSize(QSize(79, 25))
        self.button_import.setMaximumSize(QSize(16777215, 16777215))
        self.button_import.setFont(font)
        self.splitter_5.addWidget(self.button_import)
        self.button_export = QPushButton(self.splitter_5)
        self.button_export.setObjectName(u"button_export")
        self.button_export.setMinimumSize(QSize(79, 25))
        self.button_export.setMaximumSize(QSize(16777215, 16777215))
        self.button_export.setFont(font)
        self.splitter_5.addWidget(self.button_export)
        self.button_add = QPushButton(self.splitter_5)
        self.button_add.setObjectName(u"button_add")
        self.button_add.setMinimumSize(QSize(79, 25))
        self.button_add.setMaximumSize(QSize(16777215, 16777215))
        self.button_add.setFont(font)
        self.splitter_5.addWidget(self.button_add)
        self.button_det = QPushButton(self.splitter_5)
        self.button_det.setObjectName(u"button_det")
        self.button_det.setMinimumSize(QSize(79, 25))
        self.button_det.setMaximumSize(QSize(16777215, 16777215))
        self.button_det.setFont(font)
        self.splitter_5.addWidget(self.button_det)
        self.button_crc = QPushButton(self.splitter_5)
        self.button_crc.setObjectName(u"button_crc")
        self.button_crc.setMinimumSize(QSize(79, 25))
        self.button_crc.setMaximumSize(QSize(16777215, 16777215))
        self.splitter_5.addWidget(self.button_crc)

        self.verticalLayout.addWidget(self.splitter_5)

        self.splitter_9 = QSplitter(self.data_widget)
        self.splitter_9.setObjectName(u"splitter_9")
        self.splitter_9.setOrientation(Qt.Orientation.Horizontal)
        self.line = QFrame(self.splitter_9)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.splitter_9.addWidget(self.line)
        self.list_data = QListWidget(self.splitter_9)
        self.list_data.setObjectName(u"list_data")
        self.list_data.setMinimumSize(QSize(0, 500))
        self.list_data.setMaximumSize(QSize(16777215, 16777215))
        self.list_data.setFont(font1)
        self.splitter_9.addWidget(self.list_data)

        self.verticalLayout.addWidget(self.splitter_9)

        self.splitter_6 = QSplitter(self.data_widget)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setOrientation(Qt.Orientation.Horizontal)
        self.line_edit_data = QLineEdit(self.splitter_6)
        self.line_edit_data.setObjectName(u"line_edit_data")
        self.line_edit_data.setMinimumSize(QSize(0, 50))
        self.line_edit_data.setMaximumSize(QSize(16777215, 16777215))
        self.line_edit_data.setFont(font2)
        self.splitter_6.addWidget(self.line_edit_data)
        self.button_send = QPushButton(self.splitter_6)
        self.button_send.setObjectName(u"button_send")
        self.button_send.setMinimumSize(QSize(0, 50))
        self.button_send.setMaximumSize(QSize(16777215, 16777215))
        self.button_send.setFont(font)
        self.splitter_6.addWidget(self.button_send)

        self.verticalLayout.addWidget(self.splitter_6)


        self.horizontalLayout.addLayout(self.verticalLayout)


        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.button_fold_common = QPushButton(self.data_widget)
        self.button_fold_common.setObjectName(u"button_fold_common")
        self.button_fold_common.setMinimumSize(QSize(0, 0))
        self.button_fold_common.setMaximumSize(QSize(25, 130))

        self.horizontalLayout_3.addWidget(self.button_fold_common)

        self.tabWidget_common = QTabWidget(self.data_widget)
        self.tabWidget_common.setObjectName(u"tabWidget_common")
        self.tabWidget_common.setMinimumSize(QSize(0, 0))
        self.tabWidget_common.setMaximumSize(QSize(16777215, 16777215))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.gridLayout_5 = QGridLayout(self.tab)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.spi_widget = QWidget(self.tab)
        self.spi_widget.setObjectName(u"spi_widget")
        self.spi_widget.setMaximumSize(QSize(16777215, 16777215))
        self.gridLayout_7 = QGridLayout(self.spi_widget)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.splitter_13 = QSplitter(self.spi_widget)
        self.splitter_13.setObjectName(u"splitter_13")
        self.splitter_13.setOrientation(Qt.Orientation.Horizontal)
        self.label_decive = QLabel(self.splitter_13)
        self.label_decive.setObjectName(u"label_decive")
        self.label_decive.setMinimumSize(QSize(100, 30))
        self.label_decive.setMaximumSize(QSize(16777215, 16777215))
        self.label_decive.setFont(font2)
        self.splitter_13.addWidget(self.label_decive)
        self.line_device = QLineEdit(self.splitter_13)
        self.line_device.setObjectName(u"line_device")
        self.line_device.setMinimumSize(QSize(150, 30))
        self.line_device.setMaximumSize(QSize(150, 16777215))
        self.line_device.setFont(font3)
        self.line_device.setReadOnly(True)
        self.splitter_13.addWidget(self.line_device)

        self.gridLayout_7.addWidget(self.splitter_13, 0, 0, 1, 1)

        self.splitter_14 = QSplitter(self.spi_widget)
        self.splitter_14.setObjectName(u"splitter_14")
        self.splitter_14.setOrientation(Qt.Orientation.Horizontal)
        self.label_vcc = QLabel(self.splitter_14)
        self.label_vcc.setObjectName(u"label_vcc")
        self.label_vcc.setMinimumSize(QSize(113, 30))
        self.label_vcc.setFont(font2)
        self.splitter_14.addWidget(self.label_vcc)
        self.combo_box_vcc = QComboBox(self.splitter_14)
        self.combo_box_vcc.setObjectName(u"combo_box_vcc")
        self.combo_box_vcc.setMinimumSize(QSize(150, 30))
        self.combo_box_vcc.setMaximumSize(QSize(150, 16777215))
        self.combo_box_vcc.setFont(font3)
        self.splitter_14.addWidget(self.combo_box_vcc)

        self.gridLayout_7.addWidget(self.splitter_14, 1, 0, 1, 1)

        self.splitter_15 = QSplitter(self.spi_widget)
        self.splitter_15.setObjectName(u"splitter_15")
        self.splitter_15.setOrientation(Qt.Orientation.Horizontal)
        self.label_io = QLabel(self.splitter_15)
        self.label_io.setObjectName(u"label_io")
        self.label_io.setMinimumSize(QSize(113, 30))
        self.label_io.setFont(font2)
        self.splitter_15.addWidget(self.label_io)
        self.combo_box_io = QComboBox(self.splitter_15)
        self.combo_box_io.setObjectName(u"combo_box_io")
        self.combo_box_io.setMinimumSize(QSize(150, 30))
        self.combo_box_io.setMaximumSize(QSize(150, 16777215))
        self.combo_box_io.setFont(font3)
        self.splitter_15.addWidget(self.combo_box_io)

        self.gridLayout_7.addWidget(self.splitter_15, 2, 0, 1, 1)

        self.splitter_16 = QSplitter(self.spi_widget)
        self.splitter_16.setObjectName(u"splitter_16")
        self.splitter_16.setOrientation(Qt.Orientation.Horizontal)
        self.label_speed = QLabel(self.splitter_16)
        self.label_speed.setObjectName(u"label_speed")
        self.label_speed.setMinimumSize(QSize(113, 30))
        self.label_speed.setFont(font2)
        self.splitter_16.addWidget(self.label_speed)
        self.combo_box_speed = QComboBox(self.splitter_16)
        self.combo_box_speed.setObjectName(u"combo_box_speed")
        self.combo_box_speed.setMinimumSize(QSize(150, 30))
        self.combo_box_speed.setMaximumSize(QSize(150, 16777215))
        self.combo_box_speed.setFont(font3)
        self.splitter_16.addWidget(self.combo_box_speed)

        self.gridLayout_7.addWidget(self.splitter_16, 3, 0, 1, 1)

        self.splitter_17 = QSplitter(self.spi_widget)
        self.splitter_17.setObjectName(u"splitter_17")
        self.splitter_17.setOrientation(Qt.Orientation.Horizontal)
        self.label_clk = QLabel(self.splitter_17)
        self.label_clk.setObjectName(u"label_clk")
        self.label_clk.setMinimumSize(QSize(113, 30))
        self.label_clk.setFont(font2)
        self.splitter_17.addWidget(self.label_clk)
        self.combo_box_clk = QComboBox(self.splitter_17)
        self.combo_box_clk.setObjectName(u"combo_box_clk")
        self.combo_box_clk.setMinimumSize(QSize(150, 30))
        self.combo_box_clk.setMaximumSize(QSize(150, 16777215))
        self.combo_box_clk.setFont(font3)
        self.splitter_17.addWidget(self.combo_box_clk)

        self.gridLayout_7.addWidget(self.splitter_17, 4, 0, 1, 1)

        self.splitter_18 = QSplitter(self.spi_widget)
        self.splitter_18.setObjectName(u"splitter_18")
        self.splitter_18.setOrientation(Qt.Orientation.Horizontal)
        self.label_bit = QLabel(self.splitter_18)
        self.label_bit.setObjectName(u"label_bit")
        self.label_bit.setMinimumSize(QSize(113, 30))
        self.label_bit.setFont(font2)
        self.splitter_18.addWidget(self.label_bit)
        self.combo_box_bit = QComboBox(self.splitter_18)
        self.combo_box_bit.setObjectName(u"combo_box_bit")
        self.combo_box_bit.setMinimumSize(QSize(150, 30))
        self.combo_box_bit.setMaximumSize(QSize(150, 16777215))
        self.combo_box_bit.setFont(font3)
        self.splitter_18.addWidget(self.combo_box_bit)

        self.gridLayout_7.addWidget(self.splitter_18, 5, 0, 1, 1)

        self.splitter_19 = QSplitter(self.spi_widget)
        self.splitter_19.setObjectName(u"splitter_19")
        self.splitter_19.setOrientation(Qt.Orientation.Horizontal)
        self.label_s_or_q = QLabel(self.splitter_19)
        self.label_s_or_q.setObjectName(u"label_s_or_q")
        self.label_s_or_q.setMinimumSize(QSize(113, 30))
        self.label_s_or_q.setFont(font2)
        self.splitter_19.addWidget(self.label_s_or_q)
        self.combo_box_s_or_q = QComboBox(self.splitter_19)
        self.combo_box_s_or_q.setObjectName(u"combo_box_s_or_q")
        self.combo_box_s_or_q.setMinimumSize(QSize(150, 30))
        self.combo_box_s_or_q.setMaximumSize(QSize(150, 16777215))
        self.combo_box_s_or_q.setFont(font3)
        self.splitter_19.addWidget(self.combo_box_s_or_q)

        self.gridLayout_7.addWidget(self.splitter_19, 6, 0, 1, 1)

        self.splitter_20 = QSplitter(self.spi_widget)
        self.splitter_20.setObjectName(u"splitter_20")
        self.splitter_20.setOrientation(Qt.Orientation.Horizontal)
        self.label_receive_size = QLabel(self.splitter_20)
        self.label_receive_size.setObjectName(u"label_receive_size")
        self.label_receive_size.setMinimumSize(QSize(113, 30))
        font4 = QFont()
        font4.setPointSize(14)
        font4.setBold(False)
        self.label_receive_size.setFont(font4)
        self.splitter_20.addWidget(self.label_receive_size)
        self.combo_box_size = QComboBox(self.splitter_20)
        self.combo_box_size.setObjectName(u"combo_box_size")
        self.combo_box_size.setMinimumSize(QSize(150, 30))
        self.combo_box_size.setMaximumSize(QSize(150, 16777215))
        self.combo_box_size.setFont(font3)
        self.splitter_20.addWidget(self.combo_box_size)

        self.gridLayout_7.addWidget(self.splitter_20, 7, 0, 1, 1)

        self.check_box_receive = QCheckBox(self.spi_widget)
        self.check_box_receive.setObjectName(u"check_box_receive")
        self.check_box_receive.setMinimumSize(QSize(268, 30))
        self.check_box_receive.setFont(font2)

        self.gridLayout_7.addWidget(self.check_box_receive, 8, 0, 1, 1)

        self.button_receive = QPushButton(self.spi_widget)
        self.button_receive.setObjectName(u"button_receive")
        self.button_receive.setMinimumSize(QSize(268, 40))

        self.gridLayout_7.addWidget(self.button_receive, 9, 0, 1, 1)


        self.gridLayout_5.addWidget(self.spi_widget, 0, 0, 1, 1)

        self.tabWidget_common.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.formLayout = QFormLayout(self.tab_2)
        self.formLayout.setObjectName(u"formLayout")
        self.button_connect = QPushButton(self.tab_2)
        self.button_connect.setObjectName(u"button_connect")
        self.button_connect.setMaximumSize(QSize(76, 24))

        self.formLayout.setWidget(0, QFormLayout.ItemRole.LabelRole, self.button_connect)

        self.button_scan = QPushButton(self.tab_2)
        self.button_scan.setObjectName(u"button_scan")
        self.button_scan.setMaximumSize(QSize(79, 24))

        self.formLayout.setWidget(1, QFormLayout.ItemRole.LabelRole, self.button_scan)

        self.line_test_interval = QLineEdit(self.tab_2)
        self.line_test_interval.setObjectName(u"line_test_interval")
        self.line_test_interval.setMaximumSize(QSize(100, 16777215))

        self.formLayout.setWidget(2, QFormLayout.ItemRole.LabelRole, self.line_test_interval)

        self.tabWidget_common.addTab(self.tab_2, "")

        self.horizontalLayout_3.addWidget(self.tabWidget_common)


        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)


        self.gridLayout_2.addWidget(self.data_widget, 0, 0, 1, 1)


        self.gridLayout_4.addWidget(self.main_widget, 0, 0, 1, 1)

        self.stacked_widget.addWidget(self.Main)
        self.Hard = QWidget()
        self.Hard.setObjectName(u"Hard")
        self.stacked_widget.addWidget(self.Hard)
        self.Prj = QWidget()
        self.Prj.setObjectName(u"Prj")
        self.gridLayout_8 = QGridLayout(self.Prj)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.splitter_2 = QSplitter(self.Prj)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setOrientation(Qt.Orientation.Horizontal)
        self.label_prj = QLabel(self.splitter_2)
        self.label_prj.setObjectName(u"label_prj")
        self.label_prj.setMaximumSize(QSize(16777215, 50))
        font5 = QFont()
        font5.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font5.setPointSize(26)
        font5.setBold(True)
        self.label_prj.setFont(font5)
        self.splitter_2.addWidget(self.label_prj)
        self.line_prj = QLineEdit(self.splitter_2)
        self.line_prj.setObjectName(u"line_prj")
        font6 = QFont()
        font6.setPointSize(20)
        self.line_prj.setFont(font6)
        self.splitter_2.addWidget(self.line_prj)
        self.splitter_4 = QSplitter(self.splitter_2)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setOrientation(Qt.Orientation.Horizontal)
        self.button_top_import = QPushButton(self.splitter_4)
        self.button_top_import.setObjectName(u"button_top_import")
        self.button_top_import.setMaximumSize(QSize(79, 24))
        self.splitter_4.addWidget(self.button_top_import)
        self.splitter_2.addWidget(self.splitter_4)

        self.gridLayout_8.addWidget(self.splitter_2, 0, 0, 1, 1)

        self.line_2 = QFrame(self.Prj)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)

        self.gridLayout_8.addWidget(self.line_2, 1, 0, 1, 1)

        self.text_prj = QTextBrowser(self.Prj)
        self.text_prj.setObjectName(u"text_prj")
        self.text_prj.setMinimumSize(QSize(700, 0))
        self.text_prj.setMaximumSize(QSize(16777215, 16777215))
        font7 = QFont()
        font7.setFamilies([u"\u5b8b\u4f53"])
        font7.setPointSize(20)
        self.text_prj.setFont(font7)

        self.gridLayout_8.addWidget(self.text_prj, 2, 0, 1, 1)

        self.stacked_widget.addWidget(self.Prj)

        self.gridLayout_6.addWidget(self.stacked_widget, 1, 0, 1, 1)

        self.button_fold_log = QPushButton(MainForm)
        self.button_fold_log.setObjectName(u"button_fold_log")
        self.button_fold_log.setMinimumSize(QSize(40, 25))
        self.button_fold_log.setMaximumSize(QSize(40, 25))

        self.gridLayout_6.addWidget(self.button_fold_log, 2, 0, 1, 1)

        self.log_widget = QWidget(MainForm)
        self.log_widget.setObjectName(u"log_widget")
        self.gridLayout_3 = QGridLayout(self.log_widget)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.splitter_3 = QSplitter(self.log_widget)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setOrientation(Qt.Orientation.Horizontal)
        self.button_save = QPushButton(self.splitter_3)
        self.button_save.setObjectName(u"button_save")
        self.button_save.setMinimumSize(QSize(50, 25))
        self.button_save.setMaximumSize(QSize(100, 100))
        self.button_save.setFont(font)
        self.splitter_3.addWidget(self.button_save)
        self.button_clear = QPushButton(self.splitter_3)
        self.button_clear.setObjectName(u"button_clear")
        self.button_clear.setMinimumSize(QSize(50, 25))
        self.button_clear.setMaximumSize(QSize(100, 100))
        self.button_clear.setFont(font)
        self.splitter_3.addWidget(self.button_clear)

        self.gridLayout_3.addWidget(self.splitter_3, 2, 0, 1, 1)

        self.text_log = QPlainTextEdit(self.log_widget)
        self.text_log.setObjectName(u"text_log")
        self.text_log.setMinimumSize(QSize(0, 0))
        font8 = QFont()
        font8.setFamilies([u"\u5b8b\u4f53"])
        font8.setPointSize(12)
        self.text_log.setFont(font8)
        self.text_log.setFrameShadow(QFrame.Shadow.Raised)
        self.text_log.setReadOnly(True)

        self.gridLayout_3.addWidget(self.text_log, 1, 0, 1, 1)


        self.gridLayout_6.addWidget(self.log_widget, 3, 0, 1, 1)


        self.retranslateUi(MainForm)

        self.stacked_widget.setCurrentIndex(0)
        self.tabWidget_common.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainForm)
    # setupUi

    def retranslateUi(self, MainForm):
        MainForm.setWindowTitle(QCoreApplication.translate("MainForm", u"SPI\u4e0a\u4f4d\u673a", None))
        self.button_prj.setText(QCoreApplication.translate("MainForm", u"\u9879\u76ee", None))
        self.button_spi.setText(QCoreApplication.translate("MainForm", u"SPI", None))
        self.button_hard.setText(QCoreApplication.translate("MainForm", u"\u786c\u4ef6", None))
        self.button_setting.setText(QCoreApplication.translate("MainForm", u"\u8bbe\u7f6e", None))
#if QT_CONFIG(tooltip)
        self.Main.setToolTip(QCoreApplication.translate("MainForm", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.button_add_group.setText(QCoreApplication.translate("MainForm", u"\u6dfb\u52a0", None))
        self.button_del_group.setText(QCoreApplication.translate("MainForm", u"\u5220\u9664", None))
        self.button_del_select.setText(QCoreApplication.translate("MainForm", u"-", None))
        self.radio_button_order.setText(QCoreApplication.translate("MainForm", u"\u987a\u5e8f\u6267\u884c", None))
        self.radio_button_circ.setText(QCoreApplication.translate("MainForm", u"\u5faa\u73af\u6267\u884c", None))
        self.radio_button_random.setText(QCoreApplication.translate("MainForm", u"\u968f\u673a\u6267\u884c", None))
        self.label_5.setText(QCoreApplication.translate("MainForm", u"\u5ef6\u65f6(s)", None))
        self.label_2.setText(QCoreApplication.translate("MainForm", u"\u6b21\u6570", None))
        self.button_start.setText(QCoreApplication.translate("MainForm", u"\u542f\u52a8", None))
        self.button_stop.setText(QCoreApplication.translate("MainForm", u"\u7ec8\u6b62", None))
        self.label.setText(QCoreApplication.translate("MainForm", u"\u5206\u7ec4", None))
        self.button_rename.setText(QCoreApplication.translate("MainForm", u"\u91cd\u547d\u540d", None))
        self.button_import.setText(QCoreApplication.translate("MainForm", u"\u5bfc\u5165", None))
        self.button_export.setText(QCoreApplication.translate("MainForm", u"\u5bfc\u51fa", None))
        self.button_add.setText(QCoreApplication.translate("MainForm", u"\u65b0\u5efa", None))
        self.button_det.setText(QCoreApplication.translate("MainForm", u"\u5220\u9664", None))
        self.button_crc.setText(QCoreApplication.translate("MainForm", u"CRC\u6821\u9a8c", None))
        self.line_edit_data.setText("")
        self.button_send.setText(QCoreApplication.translate("MainForm", u"\u53d1\u9001", None))
        self.button_fold_common.setText(QCoreApplication.translate("MainForm", u">", None))
        self.label_decive.setText(QCoreApplication.translate("MainForm", u"\u8bbe\u5907", None))
        self.label_vcc.setText(QCoreApplication.translate("MainForm", u"VCC\u7535\u538b", None))
        self.label_io.setText(QCoreApplication.translate("MainForm", u"IO\u7535\u5e73", None))
        self.label_speed.setText(QCoreApplication.translate("MainForm", u"SPI\u901f\u7387", None))
        self.label_clk.setText(QCoreApplication.translate("MainForm", u"\u65f6\u949f", None))
        self.label_bit.setText(QCoreApplication.translate("MainForm", u"\u4f4d\u987a\u5e8f", None))
        self.label_s_or_q.setText(QCoreApplication.translate("MainForm", u"S/QSPI", None))
        self.label_receive_size.setText(QCoreApplication.translate("MainForm", u"\u8bfb\u6570\u636e\u957f\u5ea6", None))
        self.check_box_receive.setText(QCoreApplication.translate("MainForm", u"\u8bfb\u6570\u636e", None))
        self.button_receive.setText(QCoreApplication.translate("MainForm", u"\u53ea\u8bfb", None))
        self.tabWidget_common.setTabText(self.tabWidget_common.indexOf(self.tab), QCoreApplication.translate("MainForm", u"spi\u914d\u7f6e", None))
        self.button_connect.setText(QCoreApplication.translate("MainForm", u"\u8fde\u63a5", None))
        self.button_scan.setText(QCoreApplication.translate("MainForm", u"\u626b\u63cf", None))
        self.tabWidget_common.setTabText(self.tabWidget_common.indexOf(self.tab_2), QCoreApplication.translate("MainForm", u"\u5f85\u5b8c\u5584", None))
        self.label_prj.setText(QCoreApplication.translate("MainForm", u"\u9879\u76ee\u540d\u79f0", None))
        self.line_prj.setText("")
        self.button_top_import.setText(QCoreApplication.translate("MainForm", u"\u5bfc\u5165", None))
        self.text_prj.setHtml(QCoreApplication.translate("MainForm", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'\u5b8b\u4f53'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'Microsoft YaHei UI'; font-size:24pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'Microsoft YaHei UI'; font-size:24pt;\"><br /></p></body></html>", None))
        self.button_fold_log.setText(QCoreApplication.translate("MainForm", u">", None))
#if QT_CONFIG(tooltip)
        self.button_save.setToolTip(QCoreApplication.translate("MainForm", u"\u4fdd\u5b58", None))
#endif // QT_CONFIG(tooltip)
        self.button_save.setText(QCoreApplication.translate("MainForm", u"\u4fdd\u5b58", None))
#if QT_CONFIG(tooltip)
        self.button_clear.setToolTip(QCoreApplication.translate("MainForm", u"\u6e05\u9664", None))
#endif // QT_CONFIG(tooltip)
        self.button_clear.setText(QCoreApplication.translate("MainForm", u"\u6e05\u9664", None))
        self.text_log.setPlainText("")
    # retranslateUi

